# Generated by Django 3.2.21 on 2023-10-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20231018_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='logos', verbose_name='Логотип магазина'),
        ),
    ]
