# Generated by Django 3.2.21 on 2023-10-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_timediscount_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timediscount',
            name='price_with_discount',
            field=models.PositiveIntegerField(),
        ),
    ]
