# Generated by Django 3.2.21 on 2023-10-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_timediscount_price_with_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timediscount',
            old_name='price_with_discount',
            new_name='discounted_price',
        ),
    ]
