# Generated by Django 3.2.21 on 2023-10-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_price_with_discount_timediscount_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timediscount',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
