# Generated by Django 3.2.21 on 2023-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_shop_id_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='logos', verbose_name='Логотип магазина'),
        ),
    ]
