# Generated by Django 3.2.21 on 2023-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='timediscount',
            name='discount_in_currency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timediscount',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
