# Generated by Django 3.2.21 on 2023-10-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20231027_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена со скдикой'),
        ),
    ]
