# Generated by Django 3.2.21 on 2023-10-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='theme',
            field=models.CharField(choices=[('black', 'Темная'), ('white', 'Светлая'), ('blue', 'Синяя')], default='black', max_length=255, verbose_name='Тема магазина'),
        ),
    ]
