# Generated by Django 3.2.21 on 2023-11-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20231115_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
    ]
