version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - main

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - sms
    volumes:
      - .:/usr/src/app
    command: bash -c "python manage.py makemigrations --merge --noinput &&
                      python manage.py migrate --noinput && 
                      python manage.py runserver 0.0.0.0:8000"
    networks:
      - main

  sms:
    build:
      context: .
      dockerfile: docker/Dockerfile-sms
    ports:
      - "1026:1026"
    volumes:
      - .:/usr/src/sms
    command: bash -c "cd sms-service && python3 main.py"
    networks:
      - main

  redis:
     image: redis:5.0.1
     ports:
       - "6379:6379"
     networks:
       - main

  celery:
    build:
      dockerfile: docker/Dockerfile
    command: celery -A core.celery worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty
    networks:
      - main

  celery-beat:
    build:
      dockerfile: docker/Dockerfile
    command: celery -A core.celery beat -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty
    networks:
      - main


networks:
  main:
    driver: bridge
