version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    container_name: django-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    links:
      - "postgres:postgres"
    command: bash -c "python manage.py makemigrations --merge --noinput &&
                      python manage.py migrate --noinput && 
                      python manage.py runserver 0.0.0.0:8000"

  redis:
     container_name: redis
     image: redis:5.0.1
     ports:
       - "6379:6379"

  celery:
    container_name: celery
    build:
      dockerfile: docker/Dockerfile
    command: celery -A core.celery worker -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty

  celery-beat:
    container_name: celery-beat
    build:
      dockerfile: docker/Dockerfile
    command: celery -A core.celery beat -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty


networks:
  default:
    external: True
    name: default_net
