version: '3'

<<<<<<< HEAD

# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:

  postgres:
    container_name: postgres_s
=======
services:

  postgres:
    container_name: postgres
>>>>>>> bdd6c04e7bdbca2c1f5f36f0ef77b81b2d574d4a
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
<<<<<<< HEAD
=======
    ports:
      - "5432:5432"
>>>>>>> bdd6c04e7bdbca2c1f5f36f0ef77b81b2d574d4a

  app:
    container_name: django-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
<<<<<<< HEAD
    command: bash -c "python manage.py makemigrations --merge --noinput &&
                      python manage.py migrate --noinput &&
                      python manage.py runserver 0.0.0.0:8000"

  redis:
     container_name: redis_r
     image: redis:5.0.1
=======
    links:
      - "postgres:postgres"
    command: bash -c "python manage.py makemigrations --merge --noinput &&
                      python manage.py migrate --noinput && 
                      python manage.py runserver 0.0.0.0:8000"

  redis:
     container_name: redis
     image: redis:5.0.1
     ports:
       - "6379:6379"
>>>>>>> bdd6c04e7bdbca2c1f5f36f0ef77b81b2d574d4a

  celery:
    container_name: celery
    build:
<<<<<<< HEAD
      context: .
      dockerfile: docker/Dockerfile
=======
      dockerfile: docker/Dockerfile
    command: celery -A core.celery worker -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty

  celery-beat:
    container_name: celery-beat
    build:
      dockerfile: docker/Dockerfile
    command: celery -A core.celery beat -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty


networks:
  default:
    external: True
    name: default_net
>>>>>>> bdd6c04e7bdbca2c1f5f36f0ef77b81b2d574d4a
