version: '3'


# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:

  postgres:
    container_name: postgres_s
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    container_name: django-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: bash -c "python manage.py makemigrations --merge --noinput &&
                      python manage.py migrate --noinput &&
                      python manage.py runserver 0.0.0.0:8000"

  redis:
     container_name: redis_r
     image: redis:5.0.1

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: docker/Dockerfile
