version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      default_net:

  app:
    container_name: django-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: bash -c "python manage.py makemigrations --merge --noinput &&
                      python manage.py migrate --noinput && 
                      python manage.py runserver 0.0.0.0:8000"
    networks:
      default_net:

  redis:
     container_name: redis
     image: redis:5.0.1
     ports:
       - "6379:6379"
     networks:
       default_net:

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A core.celery worker -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty
    networks:
      default_net:

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A core.celery beat -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty
    networks:
      default_net:


networks:
  default_net:
    external: True
    name: esdp-ap-11
