<<<<<<< HEAD:ESDP_Project/shop/migrations/0028_alter_product_options.py
# Generated by Django 3.2.21 on 2023-11-14 11:37
=======
# Generated by Django 3.2.21 on 2023-11-14 12:06
>>>>>>> origin/docker_postgres:Core/shop/migrations/0028_alter_product_options.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_merge_20231103_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
