# Generated by Django 3.2.21 on 2023-12-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_shop_tg_token'),
        ('shop', '0037_alter_order_date'),
    ]

    operations = [
    ]
