version: '3'

services:
  sms:
    container_name: sms-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "1026:1026"
    volumes:
      - .:/usr/src/sms
    command: bash -c "python3 main.py"

networks:
  default:
    external: True
    name: default_net
