version: '3'

services:
  sms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1026:1026"
    env_file:
      - .env
    volumes:
      - .:/usr/src/sms
    command: bash -c "python3 main.py"
    networks:
      default_net:

networks:
  default_net:
    external: True
    name: esdp-ap-11
